version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        mem_limit: 2048m
        depends_on:
            - postgres
        env_file:
            - ./scripts/.env
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - TZ=Asia/Bangkok
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./test:/usr/local/airflow/test
            - ./plugins:/usr/local/airflow/plugins
            - ./scripts:/usr/local/airflow/scripts
            - ./requirements.txt:/requirements.txt
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3